### ISSUE TITLE
Add any basic python Program

### ISSUE THREAD

**Issue by cyberpvn7** [Pavan-Kamthane/Python_Lang#1]
Create a folder of your name 
then add you code

### **"How to contribute in repo and what is  PR ?"**
This is the main **AGENDA** Of this repository.

**Comment by deepanshmittal** [comment]
I would like to contribute to this.

**Comment by yogesh-9999** [comment]
Hey @Pavan-Kamthane  assign it to me

**Comment by cyberpvn7** [comment]
@yogesh-9999 u can PR directly

**Comment by MrJayendra** [comment]
I am interested in this work.
Please assign it to me.

**Comment by ShivamGarg2910** [comment]
Hi @Pavan-Kamthane, I have raised a PR: https://github.com/Pavan-Kamthane/Python_Lang/pull/25
Please review.

**Comment by ShrutiSingh04503** [comment]
Hey, I'll love to work on this issue, Would appreciate it if you assign me.

**Comment by cyberpvn7** [comment]
@ShrutiSingh04503 u can PR directly

**Comment by ShrutiSingh04503** [comment]
Hi @Pavan-Kamthane  I have created pr  https://github.com/Pavan-Kamthane/Python_Lang/pull/73
Please Check..

**Comment by Bitan-Kundu** [comment]
> Create a folder of your name then add you code
> 
> ### **"How to contribute in repo and what is PR ?"**
> This is the main **AGENDA** Of this repository.

Hello Sir, Can you assign this issue to me?
