### ISSUE TITLE
File ---> file named folder 

### ISSUE THREAD

**Issue by cyberpvn7** [Pavan-Kamthane/Python_Lang#54]
Hey guys I have one task for you.

In this repository those files which are not in folder_**(except readme.md and contribution.md)**_ , put them in folder of same filed name.
**And if they are already in folder then don't touch them.**

Example if someone added **helloworld**_program then you have to create a helloworld named folder then add this **helloworld** file, that set.

I think it is enough to explain.

Thanks.

**Comment by Dileep2608** [comment]
@Pavan-Kamthane could you assign this work to me, so that I can work on it.
And after adding the file into the folder with the same name, should we remove that file from the main repo or should we leave it there also?

**Comment by cyberpvn7** [comment]
@Dileep2608 Yes u have to remove
