### ISSUE TITLE
Upload a simple Python program in your named folder.

### ISSUE THREAD

**Issue by cyberpvn7** [Pavan-Kamthane/Python_Lang#96]
Create a folder of your name 
then add you code

### **"How to contribute in repo and what is  PR ?"**
This is the main **AGENDA** Of this repository.

**You can create a PR directly, no need to assign anyone**

**Comment by aditya-agr** [comment]
I want to add python game.
please assign it to me.

**Comment by richardnikolas** [comment]
@Pavan-Kamthane  Hey that's cool! I think I'll do that too.
